import type { DisplayLanguageCode } from "./localization";

const english = {
  deliveryBanner: "FREE SITE DELIVERY | Complimentary fleet transportation directly to your construction site across the Mbarara region on qualifying bulk orders.",
  brandTag: "Factory-direct concrete supply",
  navProducts: "Products",
  navCatalogue: "Catalogue",
  navPayments: "Payments",
  navQr: "QR Code",
  navFunding: "Funding Pack",
  navFounder: "Founder",
  navContact: "Contact",
  heroStatus: "Live plant status: quoting and dispatch planning open",
  heroTitle: "Factory-direct concrete products for serious construction across Western Uganda.",
  heroBody: "Order hollow blocks, solid blocks, pavers, kerbstones, drainage channels, culverts, and future ready-mix concrete from a disciplined Mbarara production platform built around UGX base records, multi-currency display, batch traceability, and direct site delivery.",
  viewProducts: "View products and prices",
  chatNow: "Chat now",
  statCurrencyTitle: "Multi-currency",
  statCurrencyBody: "UGX base records",
  statQcTitle: "Batch QC",
  statQcBody: "Internal crushing tests",
  statFleetTitle: "Fleet logistics",
  statFleetBody: "Direct site delivery",
  fleetEyebrow: "Fleet capability",
  fleetTitle: "Our Dedicated Heavy Fleet Services",
  metricNoFees: "Zero Haulier Fees",
  metricNoFeesBody: "Bulk orders qualify for factory-managed delivery.",
  metricDirectDelivery: "Direct-to-Site Crane/Tipper Delivery",
  metricDirectDeliveryBody: "Dispatch planning for Mbarara regional projects.",
  metricRealtime: "Real-Time Site-Arrival Dispatch",
  metricRealtimeBody: "Clear coordination before truck release.",
  cartProgressEyebrow: "Dynamic cart progress",
  cartProgressTitle: "Free Delivery Unlock Meter",
  tonnesLoaded: "tonnes loaded",
  deliveryUnlocked: "Free Factory Tipper Delivery unlocked for qualifying site radius.",
  addBlocksPrefix: "Add",
  addBlocksSuffix: "more blocks to unlock 100% Free Factory Tipper Delivery.",
  liveBasket: "Live Basket",
  quotePlanner: "Quote & Delivery Planner",
  basketEmpty: "Add products to build a quotation and send it directly by WhatsApp.",
  deliveryProgress: "Delivery progress",
  basketValue: "Basket value",
  weight: "Weight",
  sendOrderWhatsapp: "Send order on WhatsApp",
  emailQuotation: "Email quotation request",
  productCatalogue: "Product catalogue",
  productsTitle: "Products, prices, filters, and quotation basket",
  productsShown: "products shown",
  searchProduct: "Search product",
  searchPlaceholder: "Search blocks, pavers, kerbs...",
  category: "Category",
  availability: "Availability",
  unit: "Unit",
  allCategories: "All categories",
  allStatuses: "All statuses",
  allUnits: "All units",
  readyToQuote: "Ready to quote",
  quotationRequired: "Quotation required",
  blocks: "Blocks",
  pavers: "Pavers",
  precast: "Precast",
  readyMix: "Ready-mix",
  outOfStock: "Out of Stock",
  curing: "In Curing / Quality Testing",
  exWorksPrice: "Ex-works price",
  configure: "Configure",
  photos: "Photos",
  fullCatalogue: "Full product catalogue",
  galleryTitle: "One main product photo, with more views on demand",
  galleryBody: "Select a product below to view one clean display image first, then open the dropdown for the other nine catalogue views. No third-party branded website photos are used here; replace catalogue visuals only with factory-owned, licence-cleared, product-only, factory-only, or company-approved local team photos.",
  visuals: "visuals",
  displayControl: "Display control",
  choosePhoto: "Choose display photo",
  photo: "Photo",
  of: "of",
  seeMorePhotos: "See more catalogue photos",
  photoWarning: "Real buyer-facing photos should come from our factory, our customers with permission, or licensed suppliers. Do not use another company's branded images as product evidence.",
  ownerUnlockTitle: "Owner photo access",
  ownerUnlockBody: "Private upload controls are hidden from public visitors. Enter the owner passphrase to unlock local catalogue photo editing on this browser.",
  ownerPassphrase: "Owner passphrase",
  unlockOwnerMode: "Unlock owner mode",
  lockOwnerMode: "Lock owner mode",
  ownerModeActive: "Owner photo controls active",
  ownerModeNote: "Uploads are stored locally in this browser for preview. For permanent public updates, export the final photos into the project assets and redeploy.",
  replaceCurrentPhoto: "Replace current photo",
  removeUploadedPhoto: "Remove uploaded photo",
  uploadHint: "Upload JPG, PNG, or WebP product photos only. Normal visitors cannot see this control.",
  materialCalculator: "Material calculator",
  per: "per",
  lengthMetres: "Length in metres",
  widthMetres: "Width in metres",
  quantityUnits: "Quantity in units",
  concreteVolume: "Concrete volume in m3",
  concreteClass: "Concrete class",
  addToBasket: "Add to quotation basket",
  lengthError: "Enter a valid length and width for the paving area.",
  volumeError: "Enter a valid ready-mix volume.",
  unitError: "Blocks, kerbs, drainage channels, and culverts require whole-number quantities.",
  checkoutSafeguard: "Checkout safeguard",
  paymentRouteTitle: "Choose payment route",
  paymentRouteBody: "Public buyers can submit an order inquiry by WhatsApp or email. Verified contractors can request credit-account fulfilment subject to balance and approved credit limit checks.",
  directPayment: "Direct Payment",
  directPaymentBody: "Mobile Money / Cash / bank confirmation.",
  creditAccount: "Contractor Credit Account",
  creditAccountBody: "For verified customers with approved limits.",
  approvedCreditLimit: "Approved Credit Limit",
  outstandingBalance: "Current Outstanding Balance",
  remainingCredit: "Remaining Available Credit",
  cartPlusDelivery: "Cart plus delivery",
  creditBlocked: "Credit boundary reached. Please make a payment on the outstanding balance or contact the finance desk before checkout.",
  paymentAcceptable: "Payment route is currently acceptable for inquiry submission.",
  mobileMoneyEyebrow: "Mobile Money Payments",
  mobileMoneyTitle: "Pay by MTN Mobile Money or Airtel Money",
  receivingNumber: "Payment receiving number",
  mtnInstruction: "Use this number only after the factory confirms product availability, delivery date, and final invoice amount.",
  airtelRoute: "Airtel payment route",
  acceptedAfterConfirmation: "Accepted after confirmation",
  basketPaymentGuide: "Current basket payment guide",
  products: "Products",
  delivery: "Delivery",
  estimatedPayable: "Estimated payable",
  paymentSafety: "Payments must match a confirmed invoice. This protects buyers from sending money before stock, delivery radius, and truck allocation are confirmed.",
  scanShare: "Scan and share",
  qrTitle: "Website QR Code",
  qrBody: "Scan to open the permanent public website with products, catalogue visuals, inquiry form, Mobile Money details, WhatsApp links, PDF report, and videos.",
  openPublicWebsite: "Open public website",
  portalEyebrow: "Verified contractor portal preview",
  portalTitle: "B2B ledger, order tracking, and blueprint requests",
  portalSteps: "Draft|Approved|Fulfilling|Out for Delivery|Completed",
  portalUploadTitle: "Institutional Material Estimation Portal",
  portalUploadBody: "Drag-and-drop zone concept for PDF, CAD, and DWG blueprint requests up to 50MB.",
  qualityTitleOne: "Strict Internal Quality Controls & Batch Crushing Tests",
  qualityTitleCertified: "UNBS Verification Ready",
  qualityTitleTwo: "Batch logs, curing records, and dispatch traceability",
  qualityTitleThree: "Contractor, institution, hardware, and developer supply",
  qualityBodyCertified: "Official certification display can be enabled later through the global feature flag.",
  qualityBodyInternal: "Laboratory quality certificates are compiled and issued upon final batch test verification.",
  fundingEyebrow: "Investor funding pack",
  fundingTitle: "Download the complete Phase 1 funding materials",
  fundingBody: "The package uses the agreed lean-launch model: UGX 130,000,000 starter budget, UGX 128,000,000 essential Phase 1 startup cost, UGX 2,000,000 protected cash buffer, and a UGX 20,000,000 monthly profit target.",
  fundingAsk: "Funding ask",
  phaseCost: "Phase 1 cost",
  cashBuffer: "Cash buffer",
  modelNetProfit: "Model net profit",
  dataConfidence: "Data confidence: current public model uses updated cement and diesel assumptions, but market prices, supplier quotes, machinery costs, and competitor records must be re-verified before investment decisions.",
  founderEyebrow: "FOUNDER & MANAGING DIRECTOR",
  founderQuote: "Our commitment is to build a factory known for structural durability, disciplined curing, laboratory crushing tests, and reliable industrial supply across Mbarara, Western Uganda, and the wider East African growth corridor.",
  whatsappUganda: "WhatsApp Uganda",
  inquiryEyebrow: "Send inquiry",
  inquiryTitle: "Ask for price confirmation, delivery, or project supply",
  namePlaceholder: "Your name / company",
  phonePlaceholder: "Phone / WhatsApp",
  locationPlaceholder: "Project location",
  messagePlaceholder: "Tell us product, quantity, delivery location, and timing...",
  submitInquiry: "Submit inquiry",
  inquiryCaptured: "Inquiry captured on this page. For fastest response, also use WhatsApp chat now.",
  footerNote: "Displayed prices are converted estimates. Final settlement, Mobile Money payments, and bulk delivery terms must be confirmed in UGX before final order.",
  email: "Email",
  whatsappUgShort: "WhatsApp UG",
  whatsappDeShort: "WhatsApp DE",
};

export type PublicWebsiteCopy = typeof english;

const withEnglish = (overrides: Partial<PublicWebsiteCopy>): PublicWebsiteCopy => ({ ...english, ...overrides });

export const publicWebsiteCopy: Record<DisplayLanguageCode, PublicWebsiteCopy> = {
  en: english,
  en_us: english,
  en_gb: english,
  de: withEnglish({
    deliveryBanner: "KOSTENLOSE BAUSTELLENLIEFERUNG | Flottentransport direkt zu Ihrer Baustelle in der Region Mbarara bei qualifizierten Grossbestellungen.",
    brandTag: "Betonprodukte direkt ab Werk",
    navProducts: "Produkte",
    navCatalogue: "Katalog",
    navPayments: "Zahlungen",
    navQr: "QR-Code",
    navFunding: "Finanzierung",
    navFounder: "Gruender",
    navContact: "Kontakt",
    heroStatus: "Anlagenstatus: Angebote und Versandplanung sind offen",
    heroTitle: "Betonprodukte direkt ab Werk fuer anspruchsvolle Bauprojekte in Westuganda.",
    heroBody: "Bestellen Sie Hohlblocksteine, Vollsteine, Pflastersteine, Randsteine, Entwaesserungsrinnen, Durchlaesse und spaeter Transportbeton von einer disziplinierten Produktionsplattform in Mbarara mit UGX-Basisdaten, Mehrwaehrungsanzeige, Chargenrueckverfolgung und direkter Baustellenlieferung.",
    viewProducts: "Produkte und Preise ansehen",
    chatNow: "Jetzt chatten",
    statCurrencyTitle: "Mehrwaehrung",
    statCurrencyBody: "UGX-Basisdaten",
    statQcTitle: "Chargen-QS",
    statQcBody: "Interne Druckpruefungen",
    statFleetTitle: "Flottenlogistik",
    statFleetBody: "Direkte Baustellenlieferung",
    fleetEyebrow: "Flottenkapazitaet",
    fleetTitle: "Unsere eigene Schwerlast-Flotte",
    metricNoFees: "Keine externen Fuhrunternehmer-Gebuehren",
    metricNoFeesBody: "Grossbestellungen qualifizieren sich fuer werksgesteuerte Lieferung.",
    metricDirectDelivery: "Direkte Kran-/Kipperlieferung zur Baustelle",
    metricDirectDeliveryBody: "Versandplanung fuer Projekte in der Region Mbarara.",
    metricRealtime: "Echtzeit-Ankunftskoordination",
    metricRealtimeBody: "Klare Abstimmung vor Freigabe des LKW.",
    cartProgressEyebrow: "Dynamischer Warenkorb",
    cartProgressTitle: "Freilieferungs-Anzeige",
    tonnesLoaded: "Tonnen geladen",
    deliveryUnlocked: "Kostenlose Werks-Kipperlieferung fuer qualifizierte Lieferdistanz freigeschaltet.",
    addBlocksPrefix: "Fuegen Sie",
    addBlocksSuffix: "weitere Bloecke hinzu, um 100% kostenlose Werks-Kipperlieferung freizuschalten.",
    liveBasket: "Live-Warenkorb",
    quotePlanner: "Angebots- und Lieferplaner",
    basketEmpty: "Fuegen Sie Produkte hinzu, um ein Angebot zu erstellen und direkt per WhatsApp zu senden.",
    deliveryProgress: "Lieferfortschritt",
    basketValue: "Warenkorbwert",
    weight: "Gewicht",
    sendOrderWhatsapp: "Bestellung per WhatsApp senden",
    emailQuotation: "Angebotsanfrage per E-Mail",
    productCatalogue: "Produktkatalog",
    productsTitle: "Produkte, Preise, Filter und Angebotskorb",
    productsShown: "Produkte angezeigt",
    searchProduct: "Produkt suchen",
    searchPlaceholder: "Bloecke, Pflaster, Randsteine suchen...",
    category: "Kategorie",
    availability: "Verfuegbarkeit",
    unit: "Einheit",
    allCategories: "Alle Kategorien",
    allStatuses: "Alle Status",
    allUnits: "Alle Einheiten",
    readyToQuote: "Angebotsbereit",
    quotationRequired: "Angebot erforderlich",
    blocks: "Bloecke",
    pavers: "Pflastersteine",
    precast: "Fertigteile",
    readyMix: "Transportbeton",
    outOfStock: "Nicht vorratig",
    curing: "In Aushärtung / Qualitätsprüfung",
    exWorksPrice: "Ab-Werk-Preis",
    configure: "Konfigurieren",
    photos: "Fotos",
    fullCatalogue: "Vollstaendiger Produktkatalog",
    galleryTitle: "Ein Hauptfoto, weitere Ansichten bei Bedarf",
    galleryBody: "Waehlen Sie unten ein Produkt aus, sehen Sie zuerst ein sauberes Hauptbild und oeffnen Sie dann die Auswahlliste fuer neun weitere Katalogansichten. Es werden keine gebrandeten Drittanbieterfotos verwendet.",
    visuals: "Bilder",
    displayControl: "Anzeige",
    choosePhoto: "Foto auswaehlen",
    photo: "Foto",
    of: "von",
    seeMorePhotos: "Weitere Katalogfotos ansehen",
    photoWarning: "Kundenfotos muessen aus unserer Fabrik, von Kunden mit Erlaubnis oder von lizenzierten Lieferanten stammen. Keine gebrandeten Bilder anderer Firmen als Produktnachweis verwenden.",
    ownerUnlockTitle: "Inhaber-Fotozugang",
    ownerUnlockBody: "Private Upload-Steuerungen sind fuer Besucher verborgen. Geben Sie die Inhaber-Passphrase ein, um lokale Katalogfoto-Bearbeitung in diesem Browser freizuschalten.",
    ownerPassphrase: "Inhaber-Passphrase",
    unlockOwnerMode: "Inhabermodus freischalten",
    lockOwnerMode: "Inhabermodus sperren",
    ownerModeActive: "Inhaber-Fotosteuerung aktiv",
    ownerModeNote: "Uploads werden lokal in diesem Browser zur Vorschau gespeichert. Fuer dauerhafte oeffentliche Updates muessen finale Fotos in die Projektdateien uebernommen und neu deployed werden.",
    replaceCurrentPhoto: "Aktuelles Foto ersetzen",
    removeUploadedPhoto: "Hochgeladenes Foto entfernen",
    uploadHint: "Nur JPG-, PNG- oder WebP-Produktfotos hochladen. Normale Besucher sehen diese Steuerung nicht.",
    materialCalculator: "Materialrechner",
    per: "pro",
    lengthMetres: "Laenge in Metern",
    widthMetres: "Breite in Metern",
    quantityUnits: "Menge in Stueck",
    concreteVolume: "Betonvolumen in m3",
    concreteClass: "Betonklasse",
    addToBasket: "Zum Angebotskorb hinzufuegen",
    lengthError: "Geben Sie eine gueltige Laenge und Breite fuer die Pflasterflaeche ein.",
    volumeError: "Geben Sie ein gueltiges Transportbetonvolumen ein.",
    unitError: "Bloecke, Randsteine, Rinnen und Durchlaesse erfordern ganze Stueckzahlen.",
    checkoutSafeguard: "Checkout-Schutz",
    paymentRouteTitle: "Zahlungsweg waehlen",
    paymentRouteBody: "Oeffentliche Kaeufer koennen eine Anfrage per WhatsApp oder E-Mail senden. Gepruefte Bauunternehmen koennen eine Kreditkonto-Erfuellung beantragen.",
    directPayment: "Direktzahlung",
    directPaymentBody: "Mobile Money / Bar / Bankbestaetigung.",
    creditAccount: "Bauunternehmer-Kreditkonto",
    creditAccountBody: "Fuer verifizierte Kunden mit genehmigten Limits.",
    approvedCreditLimit: "Genehmigtes Kreditlimit",
    outstandingBalance: "Offener Saldo",
    remainingCredit: "Verfuegbarer Restkredit",
    cartPlusDelivery: "Warenkorb plus Lieferung",
    creditBlocked: "Kreditgrenze erreicht. Bitte begleichen Sie den offenen Saldo oder kontaktieren Sie die Finanzabteilung vor dem Checkout.",
    paymentAcceptable: "Der Zahlungsweg ist derzeit fuer die Anfrage akzeptabel.",
    mobileMoneyEyebrow: "Mobile-Money-Zahlungen",
    mobileMoneyTitle: "Zahlen mit MTN Mobile Money oder Airtel Money",
    receivingNumber: "Zahlungsempfangsnummer",
    mtnInstruction: "Diese Nummer erst verwenden, nachdem Verfuegbarkeit, Lieferdatum und Endrechnung bestaetigt wurden.",
    airtelRoute: "Airtel-Zahlungsweg",
    acceptedAfterConfirmation: "Nach Bestaetigung akzeptiert",
    basketPaymentGuide: "Aktuelle Zahlungsuebersicht",
    products: "Produkte",
    delivery: "Lieferung",
    estimatedPayable: "Geschaetzter Zahlbetrag",
    paymentSafety: "Zahlungen muessen einer bestaetigten Rechnung entsprechen. Das schuetzt Kaeufer vor Zahlungen vor bestaetigtem Lagerbestand, Lieferdistanz und LKW-Zuteilung.",
    scanShare: "Scannen und teilen",
    qrTitle: "Website-QR-Code",
    qrBody: "Scannen, um die permanente Website mit Produkten, Katalogbildern, Anfrageformular, Mobile-Money-Daten, WhatsApp-Links, PDF-Bericht und Videos zu oeffnen.",
    openPublicWebsite: "Oeffentliche Website oeffnen",
    portalEyebrow: "Vorschau verifiziertes Bauunternehmer-Portal",
    portalTitle: "B2B-Konto, Auftragsverfolgung und Plananfragen",
    portalSteps: "Entwurf|Genehmigt|In Bearbeitung|In Lieferung|Abgeschlossen",
    portalUploadTitle: "Institutionelles Material-Schaetzportal",
    portalUploadBody: "Konzept fuer Drag-and-drop von PDF-, CAD- und DWG-Plananfragen bis 50 MB.",
    fundingEyebrow: "Investoren-Finanzierungspaket",
    fundingTitle: "Komplette Phase-1-Finanzierungsunterlagen herunterladen",
    fundingAsk: "Finanzierungsbedarf",
    phaseCost: "Phase-1-Kosten",
    cashBuffer: "Liquiditaetspuffer",
    modelNetProfit: "Modell-Nettogewinn",
    founderEyebrow: "GRUENDER & GESCHAEFTSFUEHRER",
    founderQuote: "Unser Anspruch ist der Aufbau einer Fabrik, die fuer strukturelle Dauerhaftigkeit, disziplinierte Aushärtung, Labordruckpruefungen und verlaessliche industrielle Belieferung in Mbarara, Westuganda und Ostafrika bekannt ist.",
    whatsappUganda: "WhatsApp Uganda",
    inquiryEyebrow: "Anfrage senden",
    inquiryTitle: "Preisbestätigung, Lieferung oder Projektversorgung anfragen",
    namePlaceholder: "Ihr Name / Unternehmen",
    phonePlaceholder: "Telefon / WhatsApp",
    locationPlaceholder: "Projektstandort",
    messagePlaceholder: "Produkt, Menge, Lieferort und Zeitplan eingeben...",
    submitInquiry: "Anfrage absenden",
    inquiryCaptured: "Anfrage auf dieser Seite erfasst. Fuer die schnellste Antwort bitte auch WhatsApp nutzen.",
    footerNote: "Angezeigte Preise sind umgerechnete Schaetzungen. Endabrechnung, Mobile-Money-Zahlungen und Lieferbedingungen muessen vor finaler Bestellung in UGX bestaetigt werden.",
    email: "E-Mail",
  }),
  fr: withEnglish({
    brandTag: "Approvisionnement beton direct usine",
    navProducts: "Produits",
    navCatalogue: "Catalogue",
    navPayments: "Paiements",
    navFunding: "Financement",
    navFounder: "Fondateur",
    navContact: "Contact",
    heroTitle: "Produits en beton directs usine pour les chantiers serieux en Ouganda occidental.",
    viewProducts: "Voir produits et prix",
    chatNow: "Discuter maintenant",
    productCatalogue: "Catalogue produits",
    productsTitle: "Produits, prix, filtres et panier de devis",
    fullCatalogue: "Catalogue produit complet",
    mobileMoneyTitle: "Payer par MTN Mobile Money ou Airtel Money",
    fundingTitle: "Telecharger les documents complets de financement Phase 1",
    founderEyebrow: "FONDATEUR ET DIRECTEUR GENERAL",
    inquiryTitle: "Demander confirmation de prix, livraison ou fourniture de projet",
    submitInquiry: "Envoyer la demande",
  }),
  sw: withEnglish({
    brandTag: "Ugavi wa bidhaa za zege moja kwa moja kutoka kiwandani",
    navProducts: "Bidhaa",
    navCatalogue: "Katalogi",
    navPayments: "Malipo",
    navFunding: "Mfuko wa ufadhili",
    navFounder: "Mwanzilishi",
    navContact: "Mawasiliano",
    heroTitle: "Bidhaa za zege moja kwa moja kutoka kiwandani kwa ujenzi makini Magharibi mwa Uganda.",
    viewProducts: "Angalia bidhaa na bei",
    chatNow: "Ongea sasa",
    productCatalogue: "Katalogi ya bidhaa",
    productsTitle: "Bidhaa, bei, vichujio na kikapu cha nukuu",
    fullCatalogue: "Katalogi kamili ya bidhaa",
    mobileMoneyTitle: "Lipa kwa MTN Mobile Money au Airtel Money",
    fundingTitle: "Pakua nyaraka kamili za ufadhili wa Awamu ya 1",
    founderEyebrow: "MWANZILISHI NA MKURUGENZI",
    inquiryTitle: "Omba uthibitisho wa bei, usafirishaji au ugavi wa mradi",
    submitInquiry: "Tuma ombi",
  }),
  es: withEnglish({
    brandTag: "Suministro de concreto directo de fabrica",
    navProducts: "Productos",
    navCatalogue: "Catalogo",
    navPayments: "Pagos",
    navFunding: "Financiacion",
    navFounder: "Fundador",
    navContact: "Contacto",
    heroTitle: "Productos de concreto directos de fabrica para construccion seria en Uganda Occidental.",
    viewProducts: "Ver productos y precios",
    chatNow: "Chatear ahora",
    productCatalogue: "Catalogo de productos",
    productsTitle: "Productos, precios, filtros y cesta de cotizacion",
    fullCatalogue: "Catalogo completo de productos",
    mobileMoneyTitle: "Pagar con MTN Mobile Money o Airtel Money",
    fundingTitle: "Descargar materiales completos de financiacion de Fase 1",
    founderEyebrow: "FUNDADOR Y DIRECTOR GENERAL",
    inquiryTitle: "Solicitar confirmacion de precio, entrega o suministro de proyecto",
    submitInquiry: "Enviar consulta",
  }),
  zh: withEnglish({
    brandTag: "工厂直供混凝土产品",
    navProducts: "产品",
    navCatalogue: "目录",
    navPayments: "付款",
    navQr: "二维码",
    navFunding: "融资资料",
    navFounder: "创始人",
    navContact: "联系",
    heroTitle: "面向乌干达西部严肃建筑项目的工厂直供混凝土产品。",
    viewProducts: "查看产品和价格",
    chatNow: "立即咨询",
    productCatalogue: "产品目录",
    productsTitle: "产品、价格、筛选和询价篮",
    fullCatalogue: "完整产品目录",
    mobileMoneyTitle: "通过 MTN Mobile Money 或 Airtel Money 付款",
    fundingTitle: "下载完整第一阶段融资材料",
    founderEyebrow: "创始人兼董事总经理",
    inquiryTitle: "咨询价格确认、配送或项目供应",
    submitInquiry: "提交咨询",
  }),
  hi: withEnglish({
    brandTag: "फैक्ट्री से सीधे कंक्रीट सप्लाई",
    navProducts: "उत्पाद",
    navCatalogue: "कैटलॉग",
    navPayments: "भुगतान",
    navFunding: "फंडिंग पैक",
    navFounder: "संस्थापक",
    navContact: "संपर्क",
    heroTitle: "पश्चिमी युगांडा में गंभीर निर्माण के लिए फैक्ट्री-डायरेक्ट कंक्रीट उत्पाद।",
    viewProducts: "उत्पाद और कीमतें देखें",
    chatNow: "अभी चैट करें",
    productCatalogue: "उत्पाद कैटलॉग",
    productsTitle: "उत्पाद, कीमतें, फिल्टर और कोटेशन बास्केट",
    fullCatalogue: "पूर्ण उत्पाद कैटलॉग",
    mobileMoneyTitle: "MTN Mobile Money या Airtel Money से भुगतान करें",
    fundingTitle: "पूरा Phase 1 funding material डाउनलोड करें",
    founderEyebrow: "संस्थापक और प्रबंध निदेशक",
    inquiryTitle: "कीमत, डिलीवरी या प्रोजेक्ट सप्लाई के लिए पूछताछ करें",
    submitInquiry: "पूछताछ भेजें",
  }),
  ar: withEnglish({
    brandTag: "توريد منتجات خرسانية مباشرة من المصنع",
    navProducts: "المنتجات",
    navCatalogue: "الكتالوج",
    navPayments: "المدفوعات",
    navQr: "رمز QR",
    navFunding: "ملف التمويل",
    navFounder: "المؤسس",
    navContact: "اتصال",
    heroTitle: "منتجات خرسانية مباشرة من المصنع لمشاريع البناء الجادة في غرب أوغندا.",
    viewProducts: "عرض المنتجات والأسعار",
    chatNow: "تواصل الآن",
    productCatalogue: "كتالوج المنتجات",
    productsTitle: "المنتجات والأسعار والفلاتر وسلة عرض السعر",
    fullCatalogue: "كتالوج المنتجات الكامل",
    mobileMoneyTitle: "الدفع عبر MTN Mobile Money أو Airtel Money",
    fundingTitle: "تنزيل مواد تمويل المرحلة الأولى كاملة",
    founderEyebrow: "المؤسس والمدير العام",
    inquiryTitle: "اطلب تأكيد السعر أو التوصيل أو توريد المشروع",
    submitInquiry: "إرسال الاستفسار",
  }),
};

export function getPublicWebsiteCopy(code: DisplayLanguageCode): PublicWebsiteCopy {
  return publicWebsiteCopy[code] ?? english;
}
